--- 
kind: pipeline
name: LolzClang
steps: 
  - 
    commands:
      - "pacman -Syyu --noconfirm && pacman -S base-devel bison ccache clang cmake flex git libelf lld ninja openssl python3 uboot-tools bc inetutils patchelf --noconfirm"
      - "ln -s /usr/bin/core_perl/pod2man /usr/bin/pod2man"
      - "bash build_lolz.sh"
    environment: 
      GITHUB_TOKEN: 
        from_secret: github_token
      TG_BOT_TOKEN: 
        from_secret: tg_bot_token
      TG_CHATID: 
        from_secret: tg_chatid
    image: "archlinux/base"
    name: clang_builder
    trigger: 
      branch: 
        - rebase
