--- 
kind: pipeline
name: XtendedClang
steps: 
  - 
    commands:
      - "export DEBIAN_FRONTEND=noninteractive"
      - "apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential ca-certificates ccache cmake curl file flex gcc g++ git lld libelf-dev libssl-dev make ninja-build patchelf python3 texinfo u-boot-tools zlib1g-dev wget"
      - "wget https://github.com/kdrag0n/proton-clang/archive/master.tar.gz"
      - "tar -zxvf master.tar.gz"
      - "cd proton-clang-master"
      - "cp -r * /usr/"
      - "cd .."
      - "rm -rf master.tar.gz proton-clang-master"
      - "clang --version"
      - "bash build_xtended.sh"
    environment: 
      GITHUB_TOKEN: 
        from_secret: github_token
      TG_BOT_TOKEN: 
        from_secret: tg_bot_token
      TG_CHATID: 
        from_secret: tg_chatid
    image: "ubuntu:20.04"
    name: clang_builder
    trigger: 
      branch: 
        - rebase
